name: deploy gcloud functions
on: [workflow_dispatch]

defaults:
    run:
      working-directory: functions

jobs:
    run-gcloud-commands:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
                with:
                    version: 'latest'
                    project_id: ${{ secrets.GCP_PROJECT_ID }}
                    service_account_key: ${{ secrets.GCP_SA_KEY }}
            - run: gcloud info